// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeoulAir.Command.Repositories;

namespace SeoulAir.Command.Repositories.Migrations
{
    [DbContext(typeof(SeoulAirCommandDbContext))]
    [Migration("20210204214318_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeoulAir.Command.Repositories.Entities.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Endpoint")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NumOfParameters")
                        .HasColumnType("int");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Commands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0181c30-b016-4918-abbc-a55578224186"),
                            Address = "seoulair-device",
                            Controller = "AirQualitySensor",
                            Endpoint = "TurnOn",
                            HttpMethod = "PUT",
                            Name = "sensor-on",
                            NumOfParameters = 0,
                            Port = 5500
                        },
                        new
                        {
                            Id = new Guid("4f505368-6e4b-4421-a08e-6e7f5af9cd8f"),
                            Address = "seoulair-device",
                            Controller = "AirQualitySensor",
                            Endpoint = "TurnOff",
                            HttpMethod = "PUT",
                            Name = "sensor-off",
                            NumOfParameters = 0,
                            Port = 5500
                        },
                        new
                        {
                            Id = new Guid("5b4dec30-8fae-457b-8fbe-1f22cea79f2a"),
                            Address = "seoulair-device",
                            Controller = "AirQualitySensor",
                            Endpoint = "IsOn",
                            HttpMethod = "GET",
                            Name = "sensor-status",
                            NumOfParameters = 0,
                            Port = 5500
                        },
                        new
                        {
                            Id = new Guid("077ee73c-83f1-410d-b684-8faa0f2f95fe"),
                            Address = "seoulair-device",
                            Controller = "SignalLight",
                            Endpoint = "IsOn",
                            HttpMethod = "GET",
                            Name = "signal-light-status",
                            NumOfParameters = 1,
                            Port = 5500
                        },
                        new
                        {
                            Id = new Guid("628f6831-27ce-4f78-8074-e5f5f84b2077"),
                            Address = "seoulair-device",
                            Controller = "SignalLight",
                            Endpoint = "TurnOn",
                            HttpMethod = "PUT",
                            Name = "signal-light-on",
                            NumOfParameters = 1,
                            Port = 5500
                        },
                        new
                        {
                            Id = new Guid("5ed2ea37-111b-47d6-95a8-dcda5353f398"),
                            Address = "seoulair-device",
                            Controller = "SignalLight",
                            Endpoint = "TurnOff",
                            HttpMethod = "PUT",
                            Name = "signal-light-off",
                            NumOfParameters = 1,
                            Port = 5500
                        },
                        new
                        {
                            Id = new Guid("b256af9b-0b1d-4739-8c62-be90465fb7d5"),
                            Address = "seoulair-device",
                            Controller = "SignalLight",
                            Endpoint = "ActiveColor",
                            HttpMethod = "PUT",
                            Name = "change-light-color",
                            NumOfParameters = 2,
                            Port = 5500
                        },
                        new
                        {
                            Id = new Guid("b6cef9a9-ccd2-455a-a4be-6c987671af22"),
                            Address = "seoulair-data",
                            Controller = "Actuator",
                            Endpoint = "IsOn",
                            HttpMethod = "GET",
                            Name = "data-status",
                            NumOfParameters = 0,
                            Port = 5600
                        },
                        new
                        {
                            Id = new Guid("d6a05a61-b36b-4780-b611-2b7bba0c33b8"),
                            Address = "seoulair-data",
                            Controller = "Actuator",
                            Endpoint = "TurnOn",
                            HttpMethod = "PUT",
                            Name = "data-on",
                            NumOfParameters = 0,
                            Port = 5600
                        },
                        new
                        {
                            Id = new Guid("fa390861-00ba-4783-b94a-b9b84ffffad1"),
                            Address = "seoulair-data",
                            Controller = "Actuator",
                            Endpoint = "TurnOff",
                            HttpMethod = "PUT",
                            Name = "data-off",
                            NumOfParameters = 0,
                            Port = 5600
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
